FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html
COPY public/topics /usr/share/nginx/html/topics
COPY public/directory.json /usr/share/nginx/html/directory.json

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
